website/school/administrator/urls.py
from . import views

from django.urls import path

from administrator import views as GeneratePDF

app_name = "administrator"

urlpatterns = [

	path('', views.administrator, name='administrator'),
	path('session/', views.session, name='session'),
	path('add_session/', views.add_session, name='add_session'),
	path('register/', views.add_student, name='register'),
	path('add_result/', views.add_result, name='add_result'),
	path('query_result/', views.query_result, name='query_result'),
	path('query_general_result/', views.query_general_result, name='query_general_result'),
	path('generate_average/', views.generate_average, name='generate_Result'),
	path('generate_result/', views.generate_result, name='generate_result'),
	path('add_student_result/<slug:pk>/', views.add_student_result, name='add_student_result'),
	path('term/', views.term, name='term'),
	path('addterm/', views.add_term, name='add_term'),
	path('pin/', views.pin, name='pin'),
	path('change_current_session/', views.change_current_session, name='change_current_session'),
	path('check_result/', views.check_result, name='check_result'),
	path('student_result/', views.student_result, name='student_result'),
	path('generatepin/', views.generatepin, name='generatepin'),
	path('pdf/', views.get_your_copy, name='get_your_copy'),
	path('updatenews/', views.NewsUpdate, name='news_update'),
	path('generate_course/', views.generate_course, name='generate_course'),
	path('promote/', views.QueryPromoteStudent, name='promote'),
	path('promote_student/', views.PromoteStudent, name='promote_student'),
	path('query_student/', views.query_student, name='query_student'),
	path('students/', views.students, name='students'),
	path('edit_student/<slug:id>/', views.edit_student, name='edit_student'),
	path('news/', views.news, name='news'),
	path('news/<slug:slug>/', views.newsdetails, name='newsdetails'),
	path('deletenews/<slug:slug>/', views.deletenews, name='deletenews'),
	path('editnews/<slug:slug>/', views.editnews, name='editnews'),

	path('query_student_term/', views.query_student_term, name='query_student_term'),
	path('change_student_term/', views.change_student_term, name='change_student_term'),
	path('select_student/', views.select_student, name='select_student'),
	path('query_staff_check_result/', views.query_staff_check_result, name='query_staff_check_result'),
	path('staff_check_result/', views.staff_check_result, name='staff_check_result'),
	path('edit_general_result/<slug:reg>', views.edit_general_result, name='edit_general_result'),

	path('gallery/', views.gallery, name='gallery'),




]

website/school/index/urls.py
from . import views

from django.urls import path



app_name = "index"

urlpatterns = [
	path('', views.index, name='index'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('price/', views.price, name='price'),
	path('news/', views.news, name='news'),
	path('gallery/', views.gallery, name='gallery'),
	path('gallery/', views.gallery, name='gallery'),
	path('news_detail/<slug:id>/', views.news_detail, name='news_detail'),
	


]

website/school/school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('administrator/', include('administrator.urls')),
    path('accounts/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

website/school/administrator/forms.py
from django import forms
from .models import Session, Student, CurrentTerm, CurrentSession, News, GeneralResult, Gallery
from ckeditor.widgets import CKEditorWidget
#from ckeditor_uploader.widgets import CKEditorWidget, CKEditorUploadingWidget
class AddSessionForm(forms.ModelForm):
	class Meta:
		model = Session
		fields = ['date']

class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = ['surname', 'first_name', 'middle_name', 'date_of_birth', 'email', 'Registration_Number', 'Phone', 'Address', 'Gender', 'current_class', 'current_session', 'current_term']

class CurrentTermForm(forms.ModelForm):
	class Meta:
		model = CurrentTerm
		fields = ['term']

class CurrentSessionForm(forms.ModelForm):
	class Meta:
		model = CurrentSession
		fields = ['session']

class CheckResultForm(forms.Form):
	Registration_Number = forms.CharField(max_length=100)
	Pin = forms.CharField(max_length=100)

# class NewsUpdateForm(forms.ModelForm):
# 	class Meta:
# 		model = NewsUpdate
# 		fields = ['title', 'body', 'status']
# 		widgets = {
# 		'body': CKEditorWidget()
# 		}

class NewsForm(forms.ModelForm):
	class Meta:
		model = News
		fields = ['title', 'body', 'status', 'timestamp']
		widgets = {
		'body': CKEditorWidget()
		}

	
class EditGeneralResultForm(forms.ModelForm):
	class Meta:
		model = GeneralResult
		fields = ['average', 'grade', 'percentage', 'total_subject', 'position', 'active']

class GalleryForm(forms.ModelForm):
	class Meta:
		model = Gallery
		fields = ['image', 'body']

website/school/administrator/views.py
from django.shortcuts import render

from .models import Session, Myclass, Student, Student_subject, Subject, Term, GeneralResult, CurrentSession, CurrentTerm, GeneralResult, GeneratePin, SchoolLogo, News, Gallery

from .forms import AddSessionForm, StudentForm, CurrentTermForm, CurrentSessionForm, CheckResultForm, NewsForm, EditGeneralResultForm, GalleryForm

from django.shortcuts import render, get_object_or_404, redirect

from django.contrib import messages

from django.http import HttpResponseRedirect, HttpResponse,JsonResponse

from django.contrib.auth.models import User

import random

import string

from random import choice 

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404




from django.http import HttpResponse

from django.views.generic import View

from school.utils import render_to_pdf #created in step 4

from django.template.loader import get_template

from django.urls import reverse

def term(request):
	current_term = CurrentTerm.objects.get(id=1)
	all_terms = Term.objects.all()
	

	# form = TermForm(request.POST or None)
	return render(request, 'administrator/term.html', {'current_term':current_term, 'all_terms':all_terms})
def add_term(request):
	detail = CurrentTerm.objects.get(id=1)
	if request.method == 'POST':
		form  = CurrentTermForm(request.POST or None, instance = detail)
		if form.is_valid():
			form.save()
			return redirect('administrator:term')
	else:
		form = CurrentTermForm(request.POST or None)
	context = {'form':form}
	return render(request, 'administrator/addterm.html',context)
	
@login_required(login_url='/accounts/login/')
def administrator(request):
	return render(request, 'administrator/base.html', {})

def session(request):
	current_session = CurrentSession.objects.get(id=1)
	session = Session.objects.all()
	context = {'session':session, 'current_session':current_session}
	return render(request, "administrator/session.html", context)

def add_session(request):
	current_session = CurrentSession.objects.get(id=1)
	if request.method == 'POST':
		form = AddSessionForm(request.POST or None, request.FILES or None)		
		if form.is_valid():
			ok = form.save(commit = False)
			ok.save()
			messages.success(request, ok.date + ' ' + 'is successfully added.')
			return redirect('administrator:session')
	else:
		form = AddSessionForm(request.POST or None) 
	context = {'form':form,}
	return render(request, "administrator/addsession.html", context)


def change_current_session(request):
	if request.method == 'POST':
		form  = CurrentSessionForm(request.POST or None)
		if form.is_valid():

			select = form.save(commit=False)
			print(select.session)
			current_session = CurrentSession.objects.get(id=1)
			current_session.session = select.session
			current_session.save()
			messages.success(request,  'current session is successfully changed')
			return redirect('administrator:session')
	else:
		form = CurrentSessionForm(request.POST or None)
	context = {'form':form}
	return render(request, "administrator/change_current_session.html", context)


def add_student(request):
	if request.method == 'POST':
		form = StudentForm(request.POST or None, request.FILES or None)		
		if form.is_valid():
			ok = form.save(commit = False)
			print(ok.surname)
			ok.save()
			messages.success(request, ok.surname + ' ' + ok.first_name + ' ' + 'was successfully Registered')

			# add_subject(ok.pk, ok)

			return redirect('administrator:register')
	else:
		form = StudentForm(request.POST or None) 
	context = {"form": form} 
	return render(request, "administrator/register.html", context)

def generate_course(request):
	session = request.POST.get('session')
	myclass = request.POST.get('myclass')
	term = request.POST.get('term')
	subject = request.POST.get('subject')
	t = Term.objects.get(term=term)
	s = Session.objects.get(date=session)
	sub = Subject.objects.get(subject_name=subject)
	students = Student.objects.filter(current_class=myclass, current_session=s.id, current_term=t.id)
	# stu = Student_subject.objects.all()
	# for i in stu:
	# 	print(i.student)
	for i in students:
		print(i.id)
		try:
			qs = Student_subject.objects.get(student=i, Registration_Number=i.Registration_Number, subject=sub, session=s, current_class=myclass)
		except Student_subject.DoesNotExist:			
			new = Student_subject()
			new.student = i
			new.Registration_Number=i.Registration_Number
			new.subject=sub
			new.session=s
			new.term=t
			new.current_class=myclass
			new.save()

		#generate = Student_subject.objects.create(, , , , )
	return redirect('administrator:query_result')
	#return render(request, 'administrator/generatecourse.html')


def add_subject(pk, ok):

	kidergarten = ['kg1', 'kg2', 'kg3']
	primary = ['pry1', 'pry2', 'pry3', 'pry4', 'pry5']
	junoir_secondary = ['jss1', 'jss2', 'jss3']
	senoir_secondary = ['sss1', 'sss2', 'sss3']

	subject_code = ""

	current_student = Student.objects.get(pk=pk)

	if current_student.current_class in kidergarten:
		subject_code = "0"
	elif current_student.current_class in primary:
		subject_code = "1"
	elif current_student.current_class in junoir_secondary:
		subject_code = "2"
	else:
		subject_code = "3" 

	all_subject = Subject.objects.all()

	for subject in all_subject:

		if subject_code in list(subject.no):

			new = Student_subject()
			new.student = current_student
			new.subject = subject
			new.session = ok.current_session
			new.term = ok.current_term
			new.current_class = ok.current_class
			new.Registration_Number=ok.Registration_Number

			new.save()

		else:

			pass


	print("done adding subjects to students")


def add_result(request):
	session = request.POST.get('session')
	session2 = Session.objects.get(date=session)
	session_new = session2.id

	term = request.POST.get('term')
	term2 = Term.objects.get(term=term)
	term_new = term2.id

	myclass = request.POST.get('myclass')


	subject = request.POST.get('subject')
	subject2 = Subject.objects.get(subject_name=subject)
	subject_new = subject2.id

	# print(session_new, term_new, myclass, subject_new)
	qs = Student_subject.objects.filter(subject=subject_new, session=session_new, term=term_new, current_class=myclass).order_by('-average')
	# a=1
	# for i in qs:
	# 	stu = Student_subject.objects.get(id=i.id, subject=subject_new, session=session_new, term=term_new, current_class=myclass)
	# 	stu.position = a 
	# 	stu.save()
	# 	a+=1

	# 	print(stu, stu.position)


	context={'qs':qs, 'session':session, 'term':term, 'myclass':myclass, 'subject':subject}
	return render (request, 'administrator/addresult.html', context)

def query_result(request):
	term = Term.objects.all()
	session = Session.objects.all()
	myclass = Myclass.objects.all()
	subject = Subject.objects.all()
	context = {'session':session, 'term':term, 'myclass':myclass, 'subject':subject }
	return render (request, 'administrator/queryresult.html', context)


def add_student_result(request, pk):

	current_student = Student_subject.objects.get(pk = pk) 

	myform = request.POST
	first_test = myform['first_test']
	second_test = myform['second_test']
	exam = myform['exam']

	current_student.first_test = first_test
	current_student.second_test = second_test
	current_student.exam = exam
	average = int(first_test) + int(second_test) + int(exam)
	average1 = average/100
	average_new = average1 * 100
	if average_new <=40:
		grade = 'F'
	elif average_new >= 80 and average_new <= 100:
		grade = 'A' 
	elif average_new >= 70 and average_new <= 79:
		grade = 'B'
	elif average_new >= 60 and average_new <= 69:
		grade = 'C'
	elif average_new >= 50 and average_new <= 59:
		grade = 'D'


	


	current_student.average = average_new
	current_student.grade = grade
	print(grade)
	print(current_student.average)
	print(int(first_test))
	print(int(second_test))
	print(int(exam))
	current_student.save()
	context = {'grade':grade, 'average_new':average_new}	
	return JsonResponse(context)





def query_general_result(request):
	current_session = CurrentSession.objects.get(id=1)
	term = CurrentTerm.objects.get(id=1)


	return render(request, 'administrator/query_general_result.html', {'current_session':current_session, 'term':term} )


def generate_average(request):
	current_session = CurrentSession.objects.select_related('session').get(id=1)
	current_term  = CurrentTerm.objects.select_related('term').get(id=1) 
	current_class = request.POST.get('select_class')

	s = Session.objects.get(date=current_session.session)
	t = Term.objects.get(term=current_term.term)

	stu = Student.objects.filter(current_class=current_class, current_term=t.id, current_session=s.id)
	for i in stu:
		specific_sub = Student_subject.objects.filter(student=i.id)
		student = ''
		for c in specific_sub:
			student = c.student

		sub = Student_subject.objects.filter(student=i.id)
		final_total =  Student_subject.objects.filter(student=i.id).exclude(average=0).count()

		a=0
		for b in sub:
			a+=b.average
		
		test =  a 
		tot = final_total * 100
		overall = (test/tot) * 100 
		i.average = a
		i.percentage=overall
		i.total_course = final_total
		i.save()
		messages.success(request, 'average generated')
		return redirect('administrator:query_general_result')

def generate_result(request):	
	current_session = CurrentSession.objects.select_related('session').get(id=1)
	current_term  = CurrentTerm.objects.select_related('term').get(id=1) 
	current_class = request.POST.get('select_class')

	s = Session.objects.get(date=current_session.session)
	t = Term.objects.get(term=current_term.term)
	generate = Student.objects.filter(current_session=s.id, current_term=t.id, current_class=current_class).order_by('-average')
	n=1
	for i in generate:
		try:

			if i.percentage <=40:
				grade = 'F'
			elif i.percentage>= 80 and i.percentage <= 100:
				grade = 'A' 
			elif i.percentage >= 70 and i.percentage <= 79:
				grade = 'B'
			elif i.percentage >= 60 and i.percentage <= 69:
				grade = 'C'
			elif i.percentage >= 50 and i.percentage <= 59:
				grade = 'D'

website/school/templates/administrator/addterm.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}

<div class="row">
<div class="col-md-6 col-md-offset-3">
<center><h2>Change Current Term</h2></center>
<form method="post">
	{% csrf_token %}
	{{form|crispy}}


	<button type="submit" class="btn btn-primary ">Change</button> 
</form>	
</div>
</div>
{% endblock %}

website/school/templates/administrator/class.html
{% extends 'administrator/base.html' %}
{% block body %}

{% load crispy_forms_tags %}









{% if messages %}
<ul class="messages">
{% for message in messages %}
<li {% if message.tags %} class="{{message.tags}}" {% endif %} >{{message}}</li>
	{% endfor %}
</ul>
{% endif %}
<form action="{% url 'administrator:student_class' %}" method="POST">{% csrf_token %}

<table>
  

    
    <td>
    
      <select name='session1' style="width: 150px;">      
      <option>Select session</option>
      {% for i in session1 %}
        <option>{{i}}</option>
      {% endfor %}      
      </select>
<select name='term1' style="width: 150px;">      
      <option>Select Term</option>
      {% for i in term1 %}
        <option>{{i}}</option>
      {% endfor %}      
      </select>

    <select name='class1' style="width: 150px;">      
      <option>Select class</option>
      {% for i in class1 %}
        <option>{{i}}</option>
      {% endfor %}      
      </select>
    <select name='subject1' style="width: 150px;">      
      <option>Select subject</option>
      {% for i in subject1 %}
        <option>{{i}}</option>
      {% endfor %}      
      </select>
     
    </td>
    <td><input type="submit" value="Go"></td>
  
</table>  
</form>


<table>
  

    
    <td>
    
       session:{{session}}, class:{{classname}}, subject:{{subject}}, term:{{term}}
     
    </td>
  
  
</table> 

<!-- 
<form method="POST">{% csrf_token %}

  {{form|crispy}} 

 
  <button type="submit" class="btn btn-primary ">Add</button> 
  
</form> 
 -->


{% endblock %}

website/school/templates/administrator/generateposition.html
{% extends 'administrator/base.html' %}
{% block text %}
Generate Result for: 
Session: {{current_session.session}}<br>
Term: {{term.term.term}}<br>

Select class: <form action="{% url 'administrator:generate_result' %}" method="POST">{% csrf_token %}
    <select name='select_class' style="width: 150px;">
<!--       <option> Select Class</option> -->
      <option>kg1</option> 
      <option>kg2</option> 
      <option>kg3</option> 
      <option>kg1</option> 
      <option>pry1</option> 
      <option>pry2</option> 
      <option>pry3</option> 
      <option>pry4</option> 
      <option>pry5</option> 
      <option>pry6</option> 
      <option>jss1</option> 
      <option>jss2</option> 
      <option>jss3</option> 
      <option>sss1</option> 
      <option>sss2</option> 
      <option>sss3</option>       
    </select>

   <input type="submit" value="Go">
 
</form>

{% endblock %}

website/school/templates/administrator/index.html
{% extends 'administrator/base2.html' %}


{% block body %}

{% endblock %}

website/school/templates/administrator/news.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}

<div class="row">
<div class="col-md-6 col-md-offset-3">
<center><h2>Add News</h2></center>
<form method="post">
    {% csrf_token %}
    {{form|crispy}}


    <button type="submit" class="btn btn-primary ">Add News</button> 
</form> 
</div>
</div>
{% endblock %}

website/school/templates/administrator/pin.html
done

website/school/templates/administrator/query_staff_check_result.html
{% extends 'administrator/base.html' %}
{% block text %}






 <form action="{% url 'administrator:staff_check_result' %}" method="POST">{% csrf_token %}
Select Session:
    <select name='select_session' style="width: 150px;">
<!--       <option> Select Class</option> -->
    {% for i in session %}
      <option>{{i.date}}</option> 
      {% endfor %}
    </select><br>

Select Term:
    <select name='select_term' style="width: 150px;">
<!--       <option> Select Class</option> -->
    {% for i in term %}
      <option>{{i.term}}</option> 
      {% endfor %}
    </select><br>


  Select class:
    <select name='select_class' style="width: 150px;">
<!--       <option> Select Class</option> -->
      <option>kg1</option> 
      <option>kg2</option> 
      <option>kg3</option> 
      <option>kg1</option> 
      <option>pry1</option> 
      <option>pry2</option> 
      <option>pry3</option> 
      <option>pry4</option> 
      <option>pry5</option> 
      <option>pry6</option> 
      <option>jss1</option> 
      <option>jss2</option> 
      <option>jss3</option> 
      <option>sss1</option> 
      <option>sss2</option> 
      <option>sss3</option>       
    </select>

   <input type="submit" value="Go">
 
</form>





{% endblock %}

website/school/templates/administrator/query_student.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}



<form action="{% url 'administrator:students' %}" method="POST">{% csrf_token %}
  <table>
  <tr>
    <td> 
      <h4>Select Details</h4>
    <select name='session' style="width: 150px;">      
    <option>Select a session</option>
    {% for i in all_sessions %}
      <option>{{i}}</option>
    {% endfor %}      
    </select>

     <select name='class' style="width: 150px;">
      <option>kg1</option> 
      <option>kg2</option> 
      <option>kg3</option> 
      <option>kg1</option> 
      <option>pry1</option> 
      <option>pry2</option> 
      <option>pry3</option> 
      <option>pry4</option> 
      <option>pry5</option> 
      <option>pry6</option> 
      <option>jss1</option> 
      <option>jss2</option> 
      <option>jss3</option> 
      <option>sss1</option> 
      <option>sss2</option> 
      <option>sss3</option>       
    </select>


     <select name='term' style="width: 150px;">      
      <option>Select a term</option>
      {% for i in all_terms %}
        <option>{{i.term}}</option>
      {% endfor %}      
      </select>     
    </td>
   
  </tr>

</table>

   <input type="submit" value="Go">
</form>

<hr>
<form action="{% url 'administrator:select_student' %}" method="POST">{% csrf_token %}
  <table>
  <tr>
    <td> 
      <h4>Search By SurName</h4>
      <input type="text" name="surname">
    </td>
   
  </tr>

</table>

   <input type="submit" value="Go">
</form>

<hr>

<form action="{% url 'administrator:select_student' %}" method="POST">{% csrf_token %}
  <table>
  <tr>
    <td> 
      <h4>Search By Firstname</h4>
      <input type="text" name="firstname">
    </td>
   
  </tr>

</table>

   <input type="submit" value="Go">
</form>

<hr>

<form action="{% url 'administrator:select_student' %}" method="POST">{% csrf_token %}
  <table>
  <tr>
    <td> 
      <h4>Search By Middlename</h4>
      <input type="text" name="middename">
    </td>
   
  </tr>

</table>

   <input type="submit" value="Go">
</form>

<hr>

<form action="{% url 'administrator:select_student' %}" method="POST">{% csrf_token %}
  <table>
  <tr>
    <td> 
      <h4>Search By Registration Number</h4>
      <input type="text" name="registrationnumber">
    </td>
   
  </tr>

</table>

   <input type="submit" value="Go">
</form>

<hr>






{% endblock %}

website/school/templates/administrator/query_student_term.html
{% extends 'administrator/base.html' %}
{% load crispy_forms_tags %}
{% block text %}

{% if messages %}
<ul class="messages">
{% for message in messages %}
<li class="{{ message.tags }} well">{{ message }}</li>
{% endfor %}
</ul>
{% endif %}

<form action="{% url 'administrator:change_student_term' %}" method="POST">{% csrf_token %}

<table>

	<h4>Change Term From</h4>
  <h4>Current Session: {{current_session.session}}</h4>
  <tr>
    <td> 


     <select name='from_class' style="width: 150px;">
      <option>kg1</option> 
      <option>kg2</option> 
      <option>kg3</option> 
      <option>kg1</option> 
      <option>pry1</option> 
      <option>pry2</option> 
      <option>pry3</option> 
      <option>pry4</option> 
      <option>pry5</option> 
      <option>pry6</option> 
      <option>jss1</option> 
      <option>jss2</option> 
      <option>jss3</option> 
      <option>sss1</option> 
      <option>sss2</option> 
      <option>sss3</option>       
    </select>   
    </td>
    
  </tr>
</table>
  <hr>
  <hr>





  <table>
  <tr>
    <td> 
    	<h4>Change Term To</h4>


     <select name='to_term' style="width: 150px;">      
      <option>Select a term</option>
      {% for i in all_terms %}
        <option>{{i.term}}</option>
      {% endfor %}      
      </select>     
    </td>
    
  </tr>

</table>
<hr>
<hr>
  <input type="submit" value="Change">
</form>

{% endblock %}

website/school/templates/administrator/queryresult.html
{% extends 'administrator/base.html' %}
{% block text %}
{% load crispy_forms_tags %}

{% if messages %}
<ul class="messages">
{% for message in messages %}
<li class="{{ message.tags }} well">{{ message }}</li>
{% endfor %}
</ul>
{% endif %}
<form action="{% url 'administrator:add_result' %}" method="POST">{% csrf_token %}

<table>
  <tr>
    <td> 


    <select name='session' style="width: 150px;">      
    <option>Select a session</option>
    {% for i in session %}
      <option>{{i}}</option>
    {% endfor %}      
    </select>
<!-- 
    <select name='myclass' style="width: 150px;">      
    <option>Select a class</option>
    {% for i in myclass %}
      <option>{{i.myclass}}</option>
    {% endfor %}      
    </select> -->

     <select name='myclass' style="width: 150px;">
<!--       <option> Select Class</option> -->
      <option>kg1</option> 
      <option>kg2</option> 
      <option>kg3</option> 
      <option>kg1</option> 
      <option>pry1</option> 
      <option>pry2</option> 
      <option>pry3</option> 
      <option>pry4</option> 
      <option>pry5</option> 
      <option>pry6</option> 
      <option>jss1</option> 
      <option>jss2</option> 
      <option>jss3</option> 
      <option>sss1</option> 
      <option>sss2</option> 
      <option>sss3</option>       
    </select>


     <select name='term' style="width: 150px;">      
      <option>Select a term</option>
      {% for i in term %}
        <option>{{i.term}}</option>
      {% endfor %}      
      </select>


     <select name='subject' style="width: 150px;">      
      <option>Select a subject</option>
      {% for i in subject %}
        <option>{{i.subject_name}}</option>
      {% endfor %}      
      </select>
     
    </td>
    <td><input type="submit" value="Go"></td>
  </tr>
</table>
  
</form>
{% endblock %}

website/school/templates/administrator/staff_check_result.html
{% extends 'administrator/base.html' %}
{% block text %}
<h3>Result for:</h3> 
Session: {{session}}<br>
Term: {{term}}<br>
Class: {{current_class}}
<table class="table table-condensed">
    <thead>
      <tr>
        <th>Surname</th>
        <th>Middle Name</th>
        <th>First Name</th>
        <th>Reg Number</th>
        <th>Average</th>
        <th>Grade</th>
        <th>Percentage</th>
        <th>Position</th>
        <th>Total Subject</th>
         <th>Active</th>
        
        
        <th></th>


      </tr>
    </thead>
    <tbody>
    {% for i in result %}
      <tr>
        <td>{{i.surname}}</td>
        <td>{{i.middle_name}}</td>
        <td>{{i.first_name}}</td>
        <td><a href="{% url 'administrator:edit_general_result' i.Registration_Number %}">{{i.Registration_Number}}</a></td>
    <td>{{i.average}}</td>
    <td>{{i.grade}}</td>
    <td>{{i.percentage}}</td>
    <td>{{i.position}}</td>
    <td>{{i.total_subject}}</td>
    <td>{{i.active}}</td>
    

      </tr>
    {% endfor %}


    </tbody>


  </table>




{% endblock %}

website/school/templates/administrator/student.html
{% extends 'administrator/base.html' %}
{% block text %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<input style="visibility: hidden;" id='myToken' name="" value="{{csrf_token}}">
<div class="col-sm-12">
<div class="container-fluid">



  </p>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Surname</th>
        <th>Middle Name</th>
        <th>First Name</th>
        <th>Reg Number</th>
        <th>Session</th>
        <th>Term</th>
        <th>Class</th>
  
        
        <th></th>


      </tr>
    </thead>
    <tbody>
    
      {% for i in qs %}
      <tr>
          <td>{{i.surname}}</td>
          <td>{{i.middle_name}}</td>
          <td>{{i.first_name}}</td>
          <td><a href="{% url 'administrator:edit_student' i.id %}">{{i.Registration_Number}}</a></td>
          <td>{{i.current_session}}</td>
          <td>{{i.current_term}}</td>
          <td>{{i.current_class}}</td>

      </tr>
      {% endfor %}
    </tbody>


  </table>

 <!--  <button class="btn btn-primary btn-lg">Generate Position</button> -->




 <form action="{% url 'administrator:generate_course' %}" method="POST">{% csrf_token %}

<table>
  <tr>
    <td> 


    
 
     
    </td>
   
  </tr>
</table>
  
</form>


</div>
</div>
















{% endblock %}